# Site settings
title: Jakub Kvita
header-img: img/home-bg.jpg
email: kvitajakub@gmail.com
# description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
# twitter_username: kvitajakub
github_username:  kvitajakub
facebook_username:  kvitajakub

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
# gems: [jekyll-paginate]
