# Site settings
title: Jakub Kvita
header-img: img/linkedin.jpg
email: kvitajakub@gmail.com
# description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
linkedin_username: kvitajakub
github_username:  kvitajakub
facebook_username:  kvitajakub
email: kvitajakub@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 6
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "articles.html", "old_posts"]
# gems: [jekyll-paginate]
